// Protocol Buffer definitions for tfbreak plugin communication.
//
// This defines the gRPC services used for communication between tfbreak-core
// (the host) and plugins. The design follows hashicorp/go-plugin patterns.
//
// DEVIATION FROM TFLINT (see ADR-0002):
// Unlike tflint which has single GetModuleContent/GetResourceContent methods,
// tfbreak has dual methods (GetOld*/GetNew*) because it compares two
// configurations to detect breaking changes.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: plugin/proto/tfbreak.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuleSet_GetRuleSetName_FullMethodName       = "/tfbreak.RuleSet/GetRuleSetName"
	RuleSet_GetRuleSetVersion_FullMethodName    = "/tfbreak.RuleSet/GetRuleSetVersion"
	RuleSet_GetRuleNames_FullMethodName         = "/tfbreak.RuleSet/GetRuleNames"
	RuleSet_GetVersionConstraint_FullMethodName = "/tfbreak.RuleSet/GetVersionConstraint"
	RuleSet_GetConfigSchema_FullMethodName      = "/tfbreak.RuleSet/GetConfigSchema"
	RuleSet_ApplyGlobalConfig_FullMethodName    = "/tfbreak.RuleSet/ApplyGlobalConfig"
	RuleSet_ApplyConfig_FullMethodName          = "/tfbreak.RuleSet/ApplyConfig"
	RuleSet_Check_FullMethodName                = "/tfbreak.RuleSet/Check"
)

// RuleSetClient is the client API for RuleSet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuleSet is the main plugin service. The host calls these methods to:
// - Query plugin metadata (name, version, rules)
// - Configure the plugin
// - Execute rules via Check
type RuleSetClient interface {
	// GetRuleSetName returns the name of the ruleset (e.g., "azurerm").
	GetRuleSetName(ctx context.Context, in *GetRuleSetName_Request, opts ...grpc.CallOption) (*GetRuleSetName_Response, error)
	// GetRuleSetVersion returns the version of the ruleset (e.g., "0.1.0").
	GetRuleSetVersion(ctx context.Context, in *GetRuleSetVersion_Request, opts ...grpc.CallOption) (*GetRuleSetVersion_Response, error)
	// GetRuleNames returns the names of all rules in this ruleset.
	GetRuleNames(ctx context.Context, in *GetRuleNames_Request, opts ...grpc.CallOption) (*GetRuleNames_Response, error)
	// GetVersionConstraint returns the tfbreak version constraint.
	GetVersionConstraint(ctx context.Context, in *GetVersionConstraint_Request, opts ...grpc.CallOption) (*GetVersionConstraint_Response, error)
	// GetConfigSchema returns the schema for plugin-specific configuration.
	GetConfigSchema(ctx context.Context, in *GetConfigSchema_Request, opts ...grpc.CallOption) (*GetConfigSchema_Response, error)
	// ApplyGlobalConfig applies global tfbreak configuration.
	ApplyGlobalConfig(ctx context.Context, in *ApplyGlobalConfig_Request, opts ...grpc.CallOption) (*ApplyGlobalConfig_Response, error)
	// ApplyConfig applies plugin-specific configuration.
	ApplyConfig(ctx context.Context, in *ApplyConfig_Request, opts ...grpc.CallOption) (*ApplyConfig_Response, error)
	// Check executes all enabled rules.
	Check(ctx context.Context, in *Check_Request, opts ...grpc.CallOption) (*Check_Response, error)
}

type ruleSetClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleSetClient(cc grpc.ClientConnInterface) RuleSetClient {
	return &ruleSetClient{cc}
}

func (c *ruleSetClient) GetRuleSetName(ctx context.Context, in *GetRuleSetName_Request, opts ...grpc.CallOption) (*GetRuleSetName_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleSetName_Response)
	err := c.cc.Invoke(ctx, RuleSet_GetRuleSetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetClient) GetRuleSetVersion(ctx context.Context, in *GetRuleSetVersion_Request, opts ...grpc.CallOption) (*GetRuleSetVersion_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleSetVersion_Response)
	err := c.cc.Invoke(ctx, RuleSet_GetRuleSetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetClient) GetRuleNames(ctx context.Context, in *GetRuleNames_Request, opts ...grpc.CallOption) (*GetRuleNames_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuleNames_Response)
	err := c.cc.Invoke(ctx, RuleSet_GetRuleNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetClient) GetVersionConstraint(ctx context.Context, in *GetVersionConstraint_Request, opts ...grpc.CallOption) (*GetVersionConstraint_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionConstraint_Response)
	err := c.cc.Invoke(ctx, RuleSet_GetVersionConstraint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetClient) GetConfigSchema(ctx context.Context, in *GetConfigSchema_Request, opts ...grpc.CallOption) (*GetConfigSchema_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigSchema_Response)
	err := c.cc.Invoke(ctx, RuleSet_GetConfigSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetClient) ApplyGlobalConfig(ctx context.Context, in *ApplyGlobalConfig_Request, opts ...grpc.CallOption) (*ApplyGlobalConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyGlobalConfig_Response)
	err := c.cc.Invoke(ctx, RuleSet_ApplyGlobalConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetClient) ApplyConfig(ctx context.Context, in *ApplyConfig_Request, opts ...grpc.CallOption) (*ApplyConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyConfig_Response)
	err := c.cc.Invoke(ctx, RuleSet_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleSetClient) Check(ctx context.Context, in *Check_Request, opts ...grpc.CallOption) (*Check_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Check_Response)
	err := c.cc.Invoke(ctx, RuleSet_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleSetServer is the server API for RuleSet service.
// All implementations must embed UnimplementedRuleSetServer
// for forward compatibility.
//
// RuleSet is the main plugin service. The host calls these methods to:
// - Query plugin metadata (name, version, rules)
// - Configure the plugin
// - Execute rules via Check
type RuleSetServer interface {
	// GetRuleSetName returns the name of the ruleset (e.g., "azurerm").
	GetRuleSetName(context.Context, *GetRuleSetName_Request) (*GetRuleSetName_Response, error)
	// GetRuleSetVersion returns the version of the ruleset (e.g., "0.1.0").
	GetRuleSetVersion(context.Context, *GetRuleSetVersion_Request) (*GetRuleSetVersion_Response, error)
	// GetRuleNames returns the names of all rules in this ruleset.
	GetRuleNames(context.Context, *GetRuleNames_Request) (*GetRuleNames_Response, error)
	// GetVersionConstraint returns the tfbreak version constraint.
	GetVersionConstraint(context.Context, *GetVersionConstraint_Request) (*GetVersionConstraint_Response, error)
	// GetConfigSchema returns the schema for plugin-specific configuration.
	GetConfigSchema(context.Context, *GetConfigSchema_Request) (*GetConfigSchema_Response, error)
	// ApplyGlobalConfig applies global tfbreak configuration.
	ApplyGlobalConfig(context.Context, *ApplyGlobalConfig_Request) (*ApplyGlobalConfig_Response, error)
	// ApplyConfig applies plugin-specific configuration.
	ApplyConfig(context.Context, *ApplyConfig_Request) (*ApplyConfig_Response, error)
	// Check executes all enabled rules.
	Check(context.Context, *Check_Request) (*Check_Response, error)
	mustEmbedUnimplementedRuleSetServer()
}

// UnimplementedRuleSetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuleSetServer struct{}

func (UnimplementedRuleSetServer) GetRuleSetName(context.Context, *GetRuleSetName_Request) (*GetRuleSetName_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuleSetName not implemented")
}
func (UnimplementedRuleSetServer) GetRuleSetVersion(context.Context, *GetRuleSetVersion_Request) (*GetRuleSetVersion_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuleSetVersion not implemented")
}
func (UnimplementedRuleSetServer) GetRuleNames(context.Context, *GetRuleNames_Request) (*GetRuleNames_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuleNames not implemented")
}
func (UnimplementedRuleSetServer) GetVersionConstraint(context.Context, *GetVersionConstraint_Request) (*GetVersionConstraint_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersionConstraint not implemented")
}
func (UnimplementedRuleSetServer) GetConfigSchema(context.Context, *GetConfigSchema_Request) (*GetConfigSchema_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigSchema not implemented")
}
func (UnimplementedRuleSetServer) ApplyGlobalConfig(context.Context, *ApplyGlobalConfig_Request) (*ApplyGlobalConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyGlobalConfig not implemented")
}
func (UnimplementedRuleSetServer) ApplyConfig(context.Context, *ApplyConfig_Request) (*ApplyConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedRuleSetServer) Check(context.Context, *Check_Request) (*Check_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedRuleSetServer) mustEmbedUnimplementedRuleSetServer() {}
func (UnimplementedRuleSetServer) testEmbeddedByValue()                 {}

// UnsafeRuleSetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuleSetServer will
// result in compilation errors.
type UnsafeRuleSetServer interface {
	mustEmbedUnimplementedRuleSetServer()
}

func RegisterRuleSetServer(s grpc.ServiceRegistrar, srv RuleSetServer) {
	// If the following call panics, it indicates UnimplementedRuleSetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuleSet_ServiceDesc, srv)
}

func _RuleSet_GetRuleSetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleSetName_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).GetRuleSetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_GetRuleSetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).GetRuleSetName(ctx, req.(*GetRuleSetName_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSet_GetRuleSetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleSetVersion_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).GetRuleSetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_GetRuleSetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).GetRuleSetVersion(ctx, req.(*GetRuleSetVersion_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSet_GetRuleNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleNames_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).GetRuleNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_GetRuleNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).GetRuleNames(ctx, req.(*GetRuleNames_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSet_GetVersionConstraint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionConstraint_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).GetVersionConstraint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_GetVersionConstraint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).GetVersionConstraint(ctx, req.(*GetVersionConstraint_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSet_GetConfigSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigSchema_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).GetConfigSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_GetConfigSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).GetConfigSchema(ctx, req.(*GetConfigSchema_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSet_ApplyGlobalConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyGlobalConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).ApplyGlobalConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_ApplyGlobalConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).ApplyGlobalConfig(ctx, req.(*ApplyGlobalConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSet_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).ApplyConfig(ctx, req.(*ApplyConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleSet_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Check_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleSetServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuleSet_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleSetServer).Check(ctx, req.(*Check_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RuleSet_ServiceDesc is the grpc.ServiceDesc for RuleSet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuleSet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tfbreak.RuleSet",
	HandlerType: (*RuleSetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRuleSetName",
			Handler:    _RuleSet_GetRuleSetName_Handler,
		},
		{
			MethodName: "GetRuleSetVersion",
			Handler:    _RuleSet_GetRuleSetVersion_Handler,
		},
		{
			MethodName: "GetRuleNames",
			Handler:    _RuleSet_GetRuleNames_Handler,
		},
		{
			MethodName: "GetVersionConstraint",
			Handler:    _RuleSet_GetVersionConstraint_Handler,
		},
		{
			MethodName: "GetConfigSchema",
			Handler:    _RuleSet_GetConfigSchema_Handler,
		},
		{
			MethodName: "ApplyGlobalConfig",
			Handler:    _RuleSet_ApplyGlobalConfig_Handler,
		},
		{
			MethodName: "ApplyConfig",
			Handler:    _RuleSet_ApplyConfig_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _RuleSet_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/tfbreak.proto",
}

const (
	Runner_GetOldModuleContent_FullMethodName   = "/tfbreak.Runner/GetOldModuleContent"
	Runner_GetNewModuleContent_FullMethodName   = "/tfbreak.Runner/GetNewModuleContent"
	Runner_GetOldResourceContent_FullMethodName = "/tfbreak.Runner/GetOldResourceContent"
	Runner_GetNewResourceContent_FullMethodName = "/tfbreak.Runner/GetNewResourceContent"
	Runner_EmitIssue_FullMethodName             = "/tfbreak.Runner/EmitIssue"
	Runner_DecodeRuleConfig_FullMethodName      = "/tfbreak.Runner/DecodeRuleConfig"
)

// RunnerClient is the client API for Runner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runner is the callback service that plugins use to:
// - Access old and new Terraform configurations
// - Emit issues when breaking changes are detected
// - Decode rule-specific configuration
//
// DEVIATION FROM TFLINT (see ADR-0002):
// Runner provides GetOld* and GetNew* method pairs instead of single methods.
type RunnerClient interface {
	// GetOldModuleContent retrieves module content from the OLD (baseline) configuration.
	GetOldModuleContent(ctx context.Context, in *GetModuleContent_Request, opts ...grpc.CallOption) (*GetModuleContent_Response, error)
	// GetNewModuleContent retrieves module content from the NEW configuration.
	GetNewModuleContent(ctx context.Context, in *GetModuleContent_Request, opts ...grpc.CallOption) (*GetModuleContent_Response, error)
	// GetOldResourceContent retrieves resources from the OLD configuration.
	GetOldResourceContent(ctx context.Context, in *GetResourceContent_Request, opts ...grpc.CallOption) (*GetResourceContent_Response, error)
	// GetNewResourceContent retrieves resources from the NEW configuration.
	GetNewResourceContent(ctx context.Context, in *GetResourceContent_Request, opts ...grpc.CallOption) (*GetResourceContent_Response, error)
	// EmitIssue reports a finding from the rule.
	EmitIssue(ctx context.Context, in *EmitIssue_Request, opts ...grpc.CallOption) (*EmitIssue_Response, error)
	// DecodeRuleConfig retrieves and decodes rule configuration.
	DecodeRuleConfig(ctx context.Context, in *DecodeRuleConfig_Request, opts ...grpc.CallOption) (*DecodeRuleConfig_Response, error)
}

type runnerClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerClient(cc grpc.ClientConnInterface) RunnerClient {
	return &runnerClient{cc}
}

func (c *runnerClient) GetOldModuleContent(ctx context.Context, in *GetModuleContent_Request, opts ...grpc.CallOption) (*GetModuleContent_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModuleContent_Response)
	err := c.cc.Invoke(ctx, Runner_GetOldModuleContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetNewModuleContent(ctx context.Context, in *GetModuleContent_Request, opts ...grpc.CallOption) (*GetModuleContent_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModuleContent_Response)
	err := c.cc.Invoke(ctx, Runner_GetNewModuleContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetOldResourceContent(ctx context.Context, in *GetResourceContent_Request, opts ...grpc.CallOption) (*GetResourceContent_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceContent_Response)
	err := c.cc.Invoke(ctx, Runner_GetOldResourceContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) GetNewResourceContent(ctx context.Context, in *GetResourceContent_Request, opts ...grpc.CallOption) (*GetResourceContent_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResourceContent_Response)
	err := c.cc.Invoke(ctx, Runner_GetNewResourceContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) EmitIssue(ctx context.Context, in *EmitIssue_Request, opts ...grpc.CallOption) (*EmitIssue_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitIssue_Response)
	err := c.cc.Invoke(ctx, Runner_EmitIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnerClient) DecodeRuleConfig(ctx context.Context, in *DecodeRuleConfig_Request, opts ...grpc.CallOption) (*DecodeRuleConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeRuleConfig_Response)
	err := c.cc.Invoke(ctx, Runner_DecodeRuleConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnerServer is the server API for Runner service.
// All implementations must embed UnimplementedRunnerServer
// for forward compatibility.
//
// Runner is the callback service that plugins use to:
// - Access old and new Terraform configurations
// - Emit issues when breaking changes are detected
// - Decode rule-specific configuration
//
// DEVIATION FROM TFLINT (see ADR-0002):
// Runner provides GetOld* and GetNew* method pairs instead of single methods.
type RunnerServer interface {
	// GetOldModuleContent retrieves module content from the OLD (baseline) configuration.
	GetOldModuleContent(context.Context, *GetModuleContent_Request) (*GetModuleContent_Response, error)
	// GetNewModuleContent retrieves module content from the NEW configuration.
	GetNewModuleContent(context.Context, *GetModuleContent_Request) (*GetModuleContent_Response, error)
	// GetOldResourceContent retrieves resources from the OLD configuration.
	GetOldResourceContent(context.Context, *GetResourceContent_Request) (*GetResourceContent_Response, error)
	// GetNewResourceContent retrieves resources from the NEW configuration.
	GetNewResourceContent(context.Context, *GetResourceContent_Request) (*GetResourceContent_Response, error)
	// EmitIssue reports a finding from the rule.
	EmitIssue(context.Context, *EmitIssue_Request) (*EmitIssue_Response, error)
	// DecodeRuleConfig retrieves and decodes rule configuration.
	DecodeRuleConfig(context.Context, *DecodeRuleConfig_Request) (*DecodeRuleConfig_Response, error)
	mustEmbedUnimplementedRunnerServer()
}

// UnimplementedRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServer struct{}

func (UnimplementedRunnerServer) GetOldModuleContent(context.Context, *GetModuleContent_Request) (*GetModuleContent_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOldModuleContent not implemented")
}
func (UnimplementedRunnerServer) GetNewModuleContent(context.Context, *GetModuleContent_Request) (*GetModuleContent_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewModuleContent not implemented")
}
func (UnimplementedRunnerServer) GetOldResourceContent(context.Context, *GetResourceContent_Request) (*GetResourceContent_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOldResourceContent not implemented")
}
func (UnimplementedRunnerServer) GetNewResourceContent(context.Context, *GetResourceContent_Request) (*GetResourceContent_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNewResourceContent not implemented")
}
func (UnimplementedRunnerServer) EmitIssue(context.Context, *EmitIssue_Request) (*EmitIssue_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitIssue not implemented")
}
func (UnimplementedRunnerServer) DecodeRuleConfig(context.Context, *DecodeRuleConfig_Request) (*DecodeRuleConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DecodeRuleConfig not implemented")
}
func (UnimplementedRunnerServer) mustEmbedUnimplementedRunnerServer() {}
func (UnimplementedRunnerServer) testEmbeddedByValue()                {}

// UnsafeRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServer will
// result in compilation errors.
type UnsafeRunnerServer interface {
	mustEmbedUnimplementedRunnerServer()
}

func RegisterRunnerServer(s grpc.ServiceRegistrar, srv RunnerServer) {
	// If the following call panics, it indicates UnimplementedRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runner_ServiceDesc, srv)
}

func _Runner_GetOldModuleContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleContent_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetOldModuleContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_GetOldModuleContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetOldModuleContent(ctx, req.(*GetModuleContent_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetNewModuleContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleContent_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetNewModuleContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_GetNewModuleContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetNewModuleContent(ctx, req.(*GetModuleContent_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetOldResourceContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceContent_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetOldResourceContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_GetOldResourceContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetOldResourceContent(ctx, req.(*GetResourceContent_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_GetNewResourceContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceContent_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).GetNewResourceContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_GetNewResourceContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).GetNewResourceContent(ctx, req.(*GetResourceContent_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_EmitIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitIssue_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).EmitIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_EmitIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).EmitIssue(ctx, req.(*EmitIssue_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runner_DecodeRuleConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeRuleConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnerServer).DecodeRuleConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runner_DecodeRuleConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnerServer).DecodeRuleConfig(ctx, req.(*DecodeRuleConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Runner_ServiceDesc is the grpc.ServiceDesc for Runner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tfbreak.Runner",
	HandlerType: (*RunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOldModuleContent",
			Handler:    _Runner_GetOldModuleContent_Handler,
		},
		{
			MethodName: "GetNewModuleContent",
			Handler:    _Runner_GetNewModuleContent_Handler,
		},
		{
			MethodName: "GetOldResourceContent",
			Handler:    _Runner_GetOldResourceContent_Handler,
		},
		{
			MethodName: "GetNewResourceContent",
			Handler:    _Runner_GetNewResourceContent_Handler,
		},
		{
			MethodName: "EmitIssue",
			Handler:    _Runner_EmitIssue_Handler,
		},
		{
			MethodName: "DecodeRuleConfig",
			Handler:    _Runner_DecodeRuleConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/tfbreak.proto",
}
