// Protocol Buffer definitions for tfbreak plugin communication.
//
// This defines the gRPC services used for communication between tfbreak-core
// (the host) and plugins. The design follows hashicorp/go-plugin patterns.
//
// DEVIATION FROM TFLINT (see ADR-0002):
// Unlike tflint which has single GetModuleContent/GetResourceContent methods,
// tfbreak has dual methods (GetOld*/GetNew*) because it compares two
// configurations to detect breaking changes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: plugin/proto/tfbreak.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity represents issue severity levels.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_ERROR       Severity = 1
	Severity_SEVERITY_WARNING     Severity = 2
	Severity_SEVERITY_NOTICE      Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_ERROR",
		2: "SEVERITY_WARNING",
		3: "SEVERITY_NOTICE",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_ERROR":       1,
		"SEVERITY_WARNING":     2,
		"SEVERITY_NOTICE":      3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_tfbreak_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_plugin_proto_tfbreak_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{0}
}

// SchemaMode specifies how schema matching behaves.
type SchemaMode int32

const (
	SchemaMode_SCHEMA_MODE_DEFAULT         SchemaMode = 0
	SchemaMode_SCHEMA_MODE_JUST_ATTRIBUTES SchemaMode = 1
)

// Enum value maps for SchemaMode.
var (
	SchemaMode_name = map[int32]string{
		0: "SCHEMA_MODE_DEFAULT",
		1: "SCHEMA_MODE_JUST_ATTRIBUTES",
	}
	SchemaMode_value = map[string]int32{
		"SCHEMA_MODE_DEFAULT":         0,
		"SCHEMA_MODE_JUST_ATTRIBUTES": 1,
	}
)

func (x SchemaMode) Enum() *SchemaMode {
	p := new(SchemaMode)
	*p = x
	return p
}

func (x SchemaMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaMode) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_tfbreak_proto_enumTypes[1].Descriptor()
}

func (SchemaMode) Type() protoreflect.EnumType {
	return &file_plugin_proto_tfbreak_proto_enumTypes[1]
}

func (x SchemaMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaMode.Descriptor instead.
func (SchemaMode) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{1}
}

// ModuleCtxType specifies the module context for content retrieval.
type ModuleCtxType int32

const (
	ModuleCtxType_MODULE_CTX_SELF ModuleCtxType = 0
	ModuleCtxType_MODULE_CTX_ROOT ModuleCtxType = 1
	ModuleCtxType_MODULE_CTX_ALL  ModuleCtxType = 2
)

// Enum value maps for ModuleCtxType.
var (
	ModuleCtxType_name = map[int32]string{
		0: "MODULE_CTX_SELF",
		1: "MODULE_CTX_ROOT",
		2: "MODULE_CTX_ALL",
	}
	ModuleCtxType_value = map[string]int32{
		"MODULE_CTX_SELF": 0,
		"MODULE_CTX_ROOT": 1,
		"MODULE_CTX_ALL":  2,
	}
)

func (x ModuleCtxType) Enum() *ModuleCtxType {
	p := new(ModuleCtxType)
	*p = x
	return p
}

func (x ModuleCtxType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleCtxType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_tfbreak_proto_enumTypes[2].Descriptor()
}

func (ModuleCtxType) Type() protoreflect.EnumType {
	return &file_plugin_proto_tfbreak_proto_enumTypes[2]
}

func (x ModuleCtxType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleCtxType.Descriptor instead.
func (ModuleCtxType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{2}
}

// ExpandMode specifies how dynamic blocks are handled.
type ExpandMode int32

const (
	ExpandMode_EXPAND_MODE_NONE   ExpandMode = 0
	ExpandMode_EXPAND_MODE_EXPAND ExpandMode = 1
)

// Enum value maps for ExpandMode.
var (
	ExpandMode_name = map[int32]string{
		0: "EXPAND_MODE_NONE",
		1: "EXPAND_MODE_EXPAND",
	}
	ExpandMode_value = map[string]int32{
		"EXPAND_MODE_NONE":   0,
		"EXPAND_MODE_EXPAND": 1,
	}
)

func (x ExpandMode) Enum() *ExpandMode {
	p := new(ExpandMode)
	*p = x
	return p
}

func (x ExpandMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExpandMode) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_tfbreak_proto_enumTypes[3].Descriptor()
}

func (ExpandMode) Type() protoreflect.EnumType {
	return &file_plugin_proto_tfbreak_proto_enumTypes[3]
}

func (x ExpandMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExpandMode.Descriptor instead.
func (ExpandMode) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{3}
}

type GetRuleSetName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetName) Reset() {
	*x = GetRuleSetName{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetName) ProtoMessage() {}

func (x *GetRuleSetName) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetName.ProtoReflect.Descriptor instead.
func (*GetRuleSetName) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{0}
}

type GetRuleSetVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetVersion) Reset() {
	*x = GetRuleSetVersion{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetVersion) ProtoMessage() {}

func (x *GetRuleSetVersion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetVersion.ProtoReflect.Descriptor instead.
func (*GetRuleSetVersion) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{1}
}

type GetRuleNames struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleNames) Reset() {
	*x = GetRuleNames{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleNames) ProtoMessage() {}

func (x *GetRuleNames) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleNames.ProtoReflect.Descriptor instead.
func (*GetRuleNames) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{2}
}

type GetVersionConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionConstraint) Reset() {
	*x = GetVersionConstraint{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionConstraint) ProtoMessage() {}

func (x *GetVersionConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionConstraint.ProtoReflect.Descriptor instead.
func (*GetVersionConstraint) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{3}
}

type GetConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchema) Reset() {
	*x = GetConfigSchema{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchema) ProtoMessage() {}

func (x *GetConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchema.ProtoReflect.Descriptor instead.
func (*GetConfigSchema) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{4}
}

type ApplyGlobalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyGlobalConfig) Reset() {
	*x = ApplyGlobalConfig{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyGlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyGlobalConfig) ProtoMessage() {}

func (x *ApplyGlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyGlobalConfig.ProtoReflect.Descriptor instead.
func (*ApplyGlobalConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{5}
}

type ApplyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfig) Reset() {
	*x = ApplyConfig{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfig) ProtoMessage() {}

func (x *ApplyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfig.ProtoReflect.Descriptor instead.
func (*ApplyConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{6}
}

type Check struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check) Reset() {
	*x = Check{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{7}
}

type GetModuleContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleContent) Reset() {
	*x = GetModuleContent{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleContent) ProtoMessage() {}

func (x *GetModuleContent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleContent.ProtoReflect.Descriptor instead.
func (*GetModuleContent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{8}
}

type GetResourceContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceContent) Reset() {
	*x = GetResourceContent{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceContent) ProtoMessage() {}

func (x *GetResourceContent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceContent.ProtoReflect.Descriptor instead.
func (*GetResourceContent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{9}
}

type EmitIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitIssue) Reset() {
	*x = EmitIssue{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitIssue) ProtoMessage() {}

func (x *EmitIssue) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitIssue.ProtoReflect.Descriptor instead.
func (*EmitIssue) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{10}
}

type DecodeRuleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRuleConfig) Reset() {
	*x = DecodeRuleConfig{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRuleConfig) ProtoMessage() {}

func (x *DecodeRuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRuleConfig.ProtoReflect.Descriptor instead.
func (*DecodeRuleConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{11}
}

// Config represents global tfbreak configuration.
type Config struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Rules             map[string]*RuleConfig `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DisabledByDefault bool                   `protobuf:"varint,2,opt,name=disabled_by_default,json=disabledByDefault,proto3" json:"disabled_by_default,omitempty"`
	Only              []string               `protobuf:"bytes,3,rep,name=only,proto3" json:"only,omitempty"`
	PluginDir         string                 `protobuf:"bytes,4,opt,name=plugin_dir,json=pluginDir,proto3" json:"plugin_dir,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{12}
}

func (x *Config) GetRules() map[string]*RuleConfig {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Config) GetDisabledByDefault() bool {
	if x != nil {
		return x.DisabledByDefault
	}
	return false
}

func (x *Config) GetOnly() []string {
	if x != nil {
		return x.Only
	}
	return nil
}

func (x *Config) GetPluginDir() string {
	if x != nil {
		return x.PluginDir
	}
	return ""
}

// RuleConfig represents configuration for a single rule.
type RuleConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// body_bytes contains JSON-encoded HCL body for rule-specific configuration.
	BodyBytes     []byte `protobuf:"bytes,3,opt,name=body_bytes,json=bodyBytes,proto3" json:"body_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleConfig) Reset() {
	*x = RuleConfig{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleConfig) ProtoMessage() {}

func (x *RuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleConfig.ProtoReflect.Descriptor instead.
func (*RuleConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{13}
}

func (x *RuleConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RuleConfig) GetBodyBytes() []byte {
	if x != nil {
		return x.BodyBytes
	}
	return nil
}

// Rule represents a rule's metadata.
type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Severity      Severity               `protobuf:"varint,3,opt,name=severity,proto3,enum=tfbreak.Severity" json:"severity,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{14}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Rule) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Rule) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

// BodySchema represents the expected structure of an HCL body.
type BodySchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*AttributeSchema     `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Blocks        []*BlockSchema         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Mode          SchemaMode             `protobuf:"varint,3,opt,name=mode,proto3,enum=tfbreak.SchemaMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodySchema) Reset() {
	*x = BodySchema{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodySchema) ProtoMessage() {}

func (x *BodySchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodySchema.ProtoReflect.Descriptor instead.
func (*BodySchema) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{15}
}

func (x *BodySchema) GetAttributes() []*AttributeSchema {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *BodySchema) GetBlocks() []*BlockSchema {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *BodySchema) GetMode() SchemaMode {
	if x != nil {
		return x.Mode
	}
	return SchemaMode_SCHEMA_MODE_DEFAULT
}

// AttributeSchema represents an expected HCL attribute.
type AttributeSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Required      bool                   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeSchema) Reset() {
	*x = AttributeSchema{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeSchema) ProtoMessage() {}

func (x *AttributeSchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeSchema.ProtoReflect.Descriptor instead.
func (*AttributeSchema) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{16}
}

func (x *AttributeSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeSchema) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

// BlockSchema represents an expected HCL block.
type BlockSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LabelNames    []string               `protobuf:"bytes,2,rep,name=label_names,json=labelNames,proto3" json:"label_names,omitempty"`
	Body          *BodySchema            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockSchema) Reset() {
	*x = BlockSchema{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockSchema) ProtoMessage() {}

func (x *BlockSchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockSchema.ProtoReflect.Descriptor instead.
func (*BlockSchema) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{17}
}

func (x *BlockSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlockSchema) GetLabelNames() []string {
	if x != nil {
		return x.LabelNames
	}
	return nil
}

func (x *BlockSchema) GetBody() *BodySchema {
	if x != nil {
		return x.Body
	}
	return nil
}

// BodyContent represents extracted content from an HCL body.
type BodyContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    map[string]*Attribute  `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Blocks        []*Block               `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyContent) Reset() {
	*x = BodyContent{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyContent) ProtoMessage() {}

func (x *BodyContent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyContent.ProtoReflect.Descriptor instead.
func (*BodyContent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{18}
}

func (x *BodyContent) GetAttributes() map[string]*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *BodyContent) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// Attribute represents an extracted HCL attribute.
type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// expr_bytes contains the expression as a serializable format.
	// We use bytes because hcl.Expression is not directly serializable.
	ExprBytes []byte `protobuf:"bytes,2,opt,name=expr_bytes,json=exprBytes,proto3" json:"expr_bytes,omitempty"`
	Range     *Range `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	NameRange *Range `protobuf:"bytes,4,opt,name=name_range,json=nameRange,proto3" json:"name_range,omitempty"`
	// expr_value contains the evaluated value as JSON when available.
	ExprValue     []byte `protobuf:"bytes,5,opt,name=expr_value,json=exprValue,proto3" json:"expr_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{19}
}

func (x *Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attribute) GetExprBytes() []byte {
	if x != nil {
		return x.ExprBytes
	}
	return nil
}

func (x *Attribute) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Attribute) GetNameRange() *Range {
	if x != nil {
		return x.NameRange
	}
	return nil
}

func (x *Attribute) GetExprValue() []byte {
	if x != nil {
		return x.ExprValue
	}
	return nil
}

// Block represents an extracted HCL block.
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Body          *BodyContent           `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	DefRange      *Range                 `protobuf:"bytes,4,opt,name=def_range,json=defRange,proto3" json:"def_range,omitempty"`
	TypeRange     *Range                 `protobuf:"bytes,5,opt,name=type_range,json=typeRange,proto3" json:"type_range,omitempty"`
	LabelRanges   []*Range               `protobuf:"bytes,6,rep,name=label_ranges,json=labelRanges,proto3" json:"label_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{20}
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Block) GetBody() *BodyContent {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Block) GetDefRange() *Range {
	if x != nil {
		return x.DefRange
	}
	return nil
}

func (x *Block) GetTypeRange() *Range {
	if x != nil {
		return x.TypeRange
	}
	return nil
}

func (x *Block) GetLabelRanges() []*Range {
	if x != nil {
		return x.LabelRanges
	}
	return nil
}

// Range represents a source code range.
type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Start         *Position              `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *Position              `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{21}
}

func (x *Range) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Range) GetStart() *Position {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Range) GetEnd() *Position {
	if x != nil {
		return x.End
	}
	return nil
}

// Position represents a position in source code.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          int64                  `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column        int64                  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Byte          int64                  `protobuf:"varint,3,opt,name=byte,proto3" json:"byte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{22}
}

func (x *Position) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Position) GetColumn() int64 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Position) GetByte() int64 {
	if x != nil {
		return x.Byte
	}
	return 0
}

// GetModuleContentOption configures how content is retrieved.
type GetModuleContentOption struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModuleCtx        ModuleCtxType          `protobuf:"varint,1,opt,name=module_ctx,json=moduleCtx,proto3,enum=tfbreak.ModuleCtxType" json:"module_ctx,omitempty"`
	ExpandMode       ExpandMode             `protobuf:"varint,2,opt,name=expand_mode,json=expandMode,proto3,enum=tfbreak.ExpandMode" json:"expand_mode,omitempty"`
	ResourceTypeHint string                 `protobuf:"bytes,3,opt,name=resource_type_hint,json=resourceTypeHint,proto3" json:"resource_type_hint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetModuleContentOption) Reset() {
	*x = GetModuleContentOption{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleContentOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleContentOption) ProtoMessage() {}

func (x *GetModuleContentOption) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleContentOption.ProtoReflect.Descriptor instead.
func (*GetModuleContentOption) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{23}
}

func (x *GetModuleContentOption) GetModuleCtx() ModuleCtxType {
	if x != nil {
		return x.ModuleCtx
	}
	return ModuleCtxType_MODULE_CTX_SELF
}

func (x *GetModuleContentOption) GetExpandMode() ExpandMode {
	if x != nil {
		return x.ExpandMode
	}
	return ExpandMode_EXPAND_MODE_NONE
}

func (x *GetModuleContentOption) GetResourceTypeHint() string {
	if x != nil {
		return x.ResourceTypeHint
	}
	return ""
}

type GetRuleSetName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetName_Request) Reset() {
	*x = GetRuleSetName_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetName_Request) ProtoMessage() {}

func (x *GetRuleSetName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetName_Request.ProtoReflect.Descriptor instead.
func (*GetRuleSetName_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{0, 0}
}

type GetRuleSetName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetName_Response) Reset() {
	*x = GetRuleSetName_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetName_Response) ProtoMessage() {}

func (x *GetRuleSetName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetName_Response.ProtoReflect.Descriptor instead.
func (*GetRuleSetName_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetRuleSetName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRuleSetVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetVersion_Request) Reset() {
	*x = GetRuleSetVersion_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetVersion_Request) ProtoMessage() {}

func (x *GetRuleSetVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetVersion_Request.ProtoReflect.Descriptor instead.
func (*GetRuleSetVersion_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{1, 0}
}

type GetRuleSetVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleSetVersion_Response) Reset() {
	*x = GetRuleSetVersion_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleSetVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleSetVersion_Response) ProtoMessage() {}

func (x *GetRuleSetVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleSetVersion_Response.ProtoReflect.Descriptor instead.
func (*GetRuleSetVersion_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetRuleSetVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetRuleNames_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleNames_Request) Reset() {
	*x = GetRuleNames_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleNames_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleNames_Request) ProtoMessage() {}

func (x *GetRuleNames_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleNames_Request.ProtoReflect.Descriptor instead.
func (*GetRuleNames_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{2, 0}
}

type GetRuleNames_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleNames_Response) Reset() {
	*x = GetRuleNames_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleNames_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleNames_Response) ProtoMessage() {}

func (x *GetRuleNames_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleNames_Response.ProtoReflect.Descriptor instead.
func (*GetRuleNames_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetRuleNames_Response) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetVersionConstraint_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionConstraint_Request) Reset() {
	*x = GetVersionConstraint_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionConstraint_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionConstraint_Request) ProtoMessage() {}

func (x *GetVersionConstraint_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionConstraint_Request.ProtoReflect.Descriptor instead.
func (*GetVersionConstraint_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{3, 0}
}

type GetVersionConstraint_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Constraint    string                 `protobuf:"bytes,1,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionConstraint_Response) Reset() {
	*x = GetVersionConstraint_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionConstraint_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionConstraint_Response) ProtoMessage() {}

func (x *GetVersionConstraint_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionConstraint_Response.ProtoReflect.Descriptor instead.
func (*GetVersionConstraint_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetVersionConstraint_Response) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

type GetConfigSchema_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchema_Request) Reset() {
	*x = GetConfigSchema_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchema_Request) ProtoMessage() {}

func (x *GetConfigSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchema_Request.ProtoReflect.Descriptor instead.
func (*GetConfigSchema_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{4, 0}
}

type GetConfigSchema_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *BodySchema            `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigSchema_Response) Reset() {
	*x = GetConfigSchema_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigSchema_Response) ProtoMessage() {}

func (x *GetConfigSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigSchema_Response.ProtoReflect.Descriptor instead.
func (*GetConfigSchema_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetConfigSchema_Response) GetSchema() *BodySchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ApplyGlobalConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyGlobalConfig_Request) Reset() {
	*x = ApplyGlobalConfig_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyGlobalConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyGlobalConfig_Request) ProtoMessage() {}

func (x *ApplyGlobalConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyGlobalConfig_Request.ProtoReflect.Descriptor instead.
func (*ApplyGlobalConfig_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ApplyGlobalConfig_Request) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ApplyGlobalConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyGlobalConfig_Response) Reset() {
	*x = ApplyGlobalConfig_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyGlobalConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyGlobalConfig_Response) ProtoMessage() {}

func (x *ApplyGlobalConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyGlobalConfig_Response.ProtoReflect.Descriptor instead.
func (*ApplyGlobalConfig_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{5, 1}
}

type ApplyConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *BodyContent           `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfig_Request) Reset() {
	*x = ApplyConfig_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfig_Request) ProtoMessage() {}

func (x *ApplyConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfig_Request.ProtoReflect.Descriptor instead.
func (*ApplyConfig_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ApplyConfig_Request) GetContent() *BodyContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type ApplyConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyConfig_Response) Reset() {
	*x = ApplyConfig_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfig_Response) ProtoMessage() {}

func (x *ApplyConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfig_Response.ProtoReflect.Descriptor instead.
func (*ApplyConfig_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{6, 1}
}

type Check_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check_Request) Reset() {
	*x = Check_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check_Request) ProtoMessage() {}

func (x *Check_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check_Request.ProtoReflect.Descriptor instead.
func (*Check_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{7, 0}
}

type Check_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Check_Response) Reset() {
	*x = Check_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Check_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check_Response) ProtoMessage() {}

func (x *Check_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check_Response.ProtoReflect.Descriptor instead.
func (*Check_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{7, 1}
}

type GetModuleContent_Request struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Schema        *BodySchema             `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Option        *GetModuleContentOption `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleContent_Request) Reset() {
	*x = GetModuleContent_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleContent_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleContent_Request) ProtoMessage() {}

func (x *GetModuleContent_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleContent_Request.ProtoReflect.Descriptor instead.
func (*GetModuleContent_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetModuleContent_Request) GetSchema() *BodySchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *GetModuleContent_Request) GetOption() *GetModuleContentOption {
	if x != nil {
		return x.Option
	}
	return nil
}

type GetModuleContent_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *BodyContent           `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModuleContent_Response) Reset() {
	*x = GetModuleContent_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModuleContent_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModuleContent_Response) ProtoMessage() {}

func (x *GetModuleContent_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModuleContent_Response.ProtoReflect.Descriptor instead.
func (*GetModuleContent_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{8, 1}
}

func (x *GetModuleContent_Response) GetContent() *BodyContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetResourceContent_Request struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ResourceType  string                  `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Schema        *BodySchema             `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Option        *GetModuleContentOption `protobuf:"bytes,3,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceContent_Request) Reset() {
	*x = GetResourceContent_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceContent_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceContent_Request) ProtoMessage() {}

func (x *GetResourceContent_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceContent_Request.ProtoReflect.Descriptor instead.
func (*GetResourceContent_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{9, 0}
}

func (x *GetResourceContent_Request) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *GetResourceContent_Request) GetSchema() *BodySchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *GetResourceContent_Request) GetOption() *GetModuleContentOption {
	if x != nil {
		return x.Option
	}
	return nil
}

type GetResourceContent_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *BodyContent           `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceContent_Response) Reset() {
	*x = GetResourceContent_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceContent_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceContent_Response) ProtoMessage() {}

func (x *GetResourceContent_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceContent_Response.ProtoReflect.Descriptor instead.
func (*GetResourceContent_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{9, 1}
}

func (x *GetResourceContent_Response) GetContent() *BodyContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type EmitIssue_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Range         *Range                 `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitIssue_Request) Reset() {
	*x = EmitIssue_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitIssue_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitIssue_Request) ProtoMessage() {}

func (x *EmitIssue_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitIssue_Request.ProtoReflect.Descriptor instead.
func (*EmitIssue_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{10, 0}
}

func (x *EmitIssue_Request) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *EmitIssue_Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmitIssue_Request) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type EmitIssue_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitIssue_Response) Reset() {
	*x = EmitIssue_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitIssue_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitIssue_Response) ProtoMessage() {}

func (x *EmitIssue_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitIssue_Response.ProtoReflect.Descriptor instead.
func (*EmitIssue_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{10, 1}
}

type DecodeRuleConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleName      string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRuleConfig_Request) Reset() {
	*x = DecodeRuleConfig_Request{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRuleConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRuleConfig_Request) ProtoMessage() {}

func (x *DecodeRuleConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRuleConfig_Request.ProtoReflect.Descriptor instead.
func (*DecodeRuleConfig_Request) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{11, 0}
}

func (x *DecodeRuleConfig_Request) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

type DecodeRuleConfig_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config_bytes contains JSON-encoded rule configuration.
	// Returns empty bytes if no configuration is provided.
	ConfigBytes   []byte `protobuf:"bytes,1,opt,name=config_bytes,json=configBytes,proto3" json:"config_bytes,omitempty"`
	HasConfig     bool   `protobuf:"varint,2,opt,name=has_config,json=hasConfig,proto3" json:"has_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecodeRuleConfig_Response) Reset() {
	*x = DecodeRuleConfig_Response{}
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecodeRuleConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecodeRuleConfig_Response) ProtoMessage() {}

func (x *DecodeRuleConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_tfbreak_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecodeRuleConfig_Response.ProtoReflect.Descriptor instead.
func (*DecodeRuleConfig_Response) Descriptor() ([]byte, []int) {
	return file_plugin_proto_tfbreak_proto_rawDescGZIP(), []int{11, 1}
}

func (x *DecodeRuleConfig_Response) GetConfigBytes() []byte {
	if x != nil {
		return x.ConfigBytes
	}
	return nil
}

func (x *DecodeRuleConfig_Response) GetHasConfig() bool {
	if x != nil {
		return x.HasConfig
	}
	return false
}

var File_plugin_proto_tfbreak_proto protoreflect.FileDescriptor

const file_plugin_proto_tfbreak_proto_rawDesc = "" +
	"\n" +
	"\x1aplugin/proto/tfbreak.proto\x12\atfbreak\";\n" +
	"\x0eGetRuleSetName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x11GetRuleSetVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\";\n" +
	"\fGetRuleNames\x1a\t\n" +
	"\aRequest\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"M\n" +
	"\x14GetVersionConstraint\x1a\t\n" +
	"\aRequest\x1a*\n" +
	"\bResponse\x12\x1e\n" +
	"\n" +
	"constraint\x18\x01 \x01(\tR\n" +
	"constraint\"U\n" +
	"\x0fGetConfigSchema\x1a\t\n" +
	"\aRequest\x1a7\n" +
	"\bResponse\x12+\n" +
	"\x06schema\x18\x01 \x01(\v2\x13.tfbreak.BodySchemaR\x06schema\"S\n" +
	"\x11ApplyGlobalConfig\x1a2\n" +
	"\aRequest\x12'\n" +
	"\x06config\x18\x01 \x01(\v2\x0f.tfbreak.ConfigR\x06config\x1a\n" +
	"\n" +
	"\bResponse\"T\n" +
	"\vApplyConfig\x1a9\n" +
	"\aRequest\x12.\n" +
	"\acontent\x18\x01 \x01(\v2\x14.tfbreak.BodyContentR\acontent\x1a\n" +
	"\n" +
	"\bResponse\"\x1e\n" +
	"\x05Check\x1a\t\n" +
	"\aRequest\x1a\n" +
	"\n" +
	"\bResponse\"\xbf\x01\n" +
	"\x10GetModuleContent\x1ao\n" +
	"\aRequest\x12+\n" +
	"\x06schema\x18\x01 \x01(\v2\x13.tfbreak.BodySchemaR\x06schema\x127\n" +
	"\x06option\x18\x02 \x01(\v2\x1f.tfbreak.GetModuleContentOptionR\x06option\x1a:\n" +
	"\bResponse\x12.\n" +
	"\acontent\x18\x01 \x01(\v2\x14.tfbreak.BodyContentR\acontent\"\xe7\x01\n" +
	"\x12GetResourceContent\x1a\x94\x01\n" +
	"\aRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12+\n" +
	"\x06schema\x18\x02 \x01(\v2\x13.tfbreak.BodySchemaR\x06schema\x127\n" +
	"\x06option\x18\x03 \x01(\v2\x1f.tfbreak.GetModuleContentOptionR\x06option\x1a:\n" +
	"\bResponse\x12.\n" +
	"\acontent\x18\x01 \x01(\v2\x14.tfbreak.BodyContentR\acontent\"\x85\x01\n" +
	"\tEmitIssue\x1al\n" +
	"\aRequest\x12!\n" +
	"\x04rule\x18\x01 \x01(\v2\r.tfbreak.RuleR\x04rule\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x05range\x18\x03 \x01(\v2\x0e.tfbreak.RangeR\x05range\x1a\n" +
	"\n" +
	"\bResponse\"\x88\x01\n" +
	"\x10DecodeRuleConfig\x1a&\n" +
	"\aRequest\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x1aL\n" +
	"\bResponse\x12!\n" +
	"\fconfig_bytes\x18\x01 \x01(\fR\vconfigBytes\x12\x1d\n" +
	"\n" +
	"has_config\x18\x02 \x01(\bR\thasConfig\"\xec\x01\n" +
	"\x06Config\x120\n" +
	"\x05rules\x18\x01 \x03(\v2\x1a.tfbreak.Config.RulesEntryR\x05rules\x12.\n" +
	"\x13disabled_by_default\x18\x02 \x01(\bR\x11disabledByDefault\x12\x12\n" +
	"\x04only\x18\x03 \x03(\tR\x04only\x12\x1d\n" +
	"\n" +
	"plugin_dir\x18\x04 \x01(\tR\tpluginDir\x1aM\n" +
	"\n" +
	"RulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tfbreak.RuleConfigR\x05value:\x028\x01\"Y\n" +
	"\n" +
	"RuleConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"body_bytes\x18\x03 \x01(\fR\tbodyBytes\"w\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12-\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x11.tfbreak.SeverityR\bseverity\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\"\x9d\x01\n" +
	"\n" +
	"BodySchema\x128\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x18.tfbreak.AttributeSchemaR\n" +
	"attributes\x12,\n" +
	"\x06blocks\x18\x02 \x03(\v2\x14.tfbreak.BlockSchemaR\x06blocks\x12'\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x13.tfbreak.SchemaModeR\x04mode\"A\n" +
	"\x0fAttributeSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\"k\n" +
	"\vBlockSchema\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vlabel_names\x18\x02 \x03(\tR\n" +
	"labelNames\x12'\n" +
	"\x04body\x18\x03 \x01(\v2\x13.tfbreak.BodySchemaR\x04body\"\xce\x01\n" +
	"\vBodyContent\x12D\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2$.tfbreak.BodyContent.AttributesEntryR\n" +
	"attributes\x12&\n" +
	"\x06blocks\x18\x02 \x03(\v2\x0e.tfbreak.BlockR\x06blocks\x1aQ\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.tfbreak.AttributeR\x05value:\x028\x01\"\xb2\x01\n" +
	"\tAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"expr_bytes\x18\x02 \x01(\fR\texprBytes\x12$\n" +
	"\x05range\x18\x03 \x01(\v2\x0e.tfbreak.RangeR\x05range\x12-\n" +
	"\n" +
	"name_range\x18\x04 \x01(\v2\x0e.tfbreak.RangeR\tnameRange\x12\x1d\n" +
	"\n" +
	"expr_value\x18\x05 \x01(\fR\texprValue\"\xec\x01\n" +
	"\x05Block\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\x12(\n" +
	"\x04body\x18\x03 \x01(\v2\x14.tfbreak.BodyContentR\x04body\x12+\n" +
	"\tdef_range\x18\x04 \x01(\v2\x0e.tfbreak.RangeR\bdefRange\x12-\n" +
	"\n" +
	"type_range\x18\x05 \x01(\v2\x0e.tfbreak.RangeR\ttypeRange\x121\n" +
	"\flabel_ranges\x18\x06 \x03(\v2\x0e.tfbreak.RangeR\vlabelRanges\"q\n" +
	"\x05Range\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12'\n" +
	"\x05start\x18\x02 \x01(\v2\x11.tfbreak.PositionR\x05start\x12#\n" +
	"\x03end\x18\x03 \x01(\v2\x11.tfbreak.PositionR\x03end\"J\n" +
	"\bPosition\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x03R\x04line\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x03R\x06column\x12\x12\n" +
	"\x04byte\x18\x03 \x01(\x03R\x04byte\"\xb3\x01\n" +
	"\x16GetModuleContentOption\x125\n" +
	"\n" +
	"module_ctx\x18\x01 \x01(\x0e2\x16.tfbreak.ModuleCtxTypeR\tmoduleCtx\x124\n" +
	"\vexpand_mode\x18\x02 \x01(\x0e2\x13.tfbreak.ExpandModeR\n" +
	"expandMode\x12,\n" +
	"\x12resource_type_hint\x18\x03 \x01(\tR\x10resourceTypeHint*c\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x01\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_NOTICE\x10\x03*F\n" +
	"\n" +
	"SchemaMode\x12\x17\n" +
	"\x13SCHEMA_MODE_DEFAULT\x10\x00\x12\x1f\n" +
	"\x1bSCHEMA_MODE_JUST_ATTRIBUTES\x10\x01*M\n" +
	"\rModuleCtxType\x12\x13\n" +
	"\x0fMODULE_CTX_SELF\x10\x00\x12\x13\n" +
	"\x0fMODULE_CTX_ROOT\x10\x01\x12\x12\n" +
	"\x0eMODULE_CTX_ALL\x10\x02*:\n" +
	"\n" +
	"ExpandMode\x12\x14\n" +
	"\x10EXPAND_MODE_NONE\x10\x00\x12\x16\n" +
	"\x12EXPAND_MODE_EXPAND\x10\x012\xae\x05\n" +
	"\aRuleSet\x12S\n" +
	"\x0eGetRuleSetName\x12\x1f.tfbreak.GetRuleSetName.Request\x1a .tfbreak.GetRuleSetName.Response\x12\\\n" +
	"\x11GetRuleSetVersion\x12\".tfbreak.GetRuleSetVersion.Request\x1a#.tfbreak.GetRuleSetVersion.Response\x12M\n" +
	"\fGetRuleNames\x12\x1d.tfbreak.GetRuleNames.Request\x1a\x1e.tfbreak.GetRuleNames.Response\x12e\n" +
	"\x14GetVersionConstraint\x12%.tfbreak.GetVersionConstraint.Request\x1a&.tfbreak.GetVersionConstraint.Response\x12V\n" +
	"\x0fGetConfigSchema\x12 .tfbreak.GetConfigSchema.Request\x1a!.tfbreak.GetConfigSchema.Response\x12\\\n" +
	"\x11ApplyGlobalConfig\x12\".tfbreak.ApplyGlobalConfig.Request\x1a#.tfbreak.ApplyGlobalConfig.Response\x12J\n" +
	"\vApplyConfig\x12\x1c.tfbreak.ApplyConfig.Request\x1a\x1d.tfbreak.ApplyConfig.Response\x128\n" +
	"\x05Check\x12\x16.tfbreak.Check.Request\x1a\x17.tfbreak.Check.Response2\xad\x04\n" +
	"\x06Runner\x12\\\n" +
	"\x13GetOldModuleContent\x12!.tfbreak.GetModuleContent.Request\x1a\".tfbreak.GetModuleContent.Response\x12\\\n" +
	"\x13GetNewModuleContent\x12!.tfbreak.GetModuleContent.Request\x1a\".tfbreak.GetModuleContent.Response\x12b\n" +
	"\x15GetOldResourceContent\x12#.tfbreak.GetResourceContent.Request\x1a$.tfbreak.GetResourceContent.Response\x12b\n" +
	"\x15GetNewResourceContent\x12#.tfbreak.GetResourceContent.Request\x1a$.tfbreak.GetResourceContent.Response\x12D\n" +
	"\tEmitIssue\x12\x1a.tfbreak.EmitIssue.Request\x1a\x1b.tfbreak.EmitIssue.Response\x12Y\n" +
	"\x10DecodeRuleConfig\x12!.tfbreak.DecodeRuleConfig.Request\x1a\".tfbreak.DecodeRuleConfig.ResponseB3Z1github.com/jokarl/tfbreak-plugin-sdk/plugin/protob\x06proto3"

var (
	file_plugin_proto_tfbreak_proto_rawDescOnce sync.Once
	file_plugin_proto_tfbreak_proto_rawDescData []byte
)

func file_plugin_proto_tfbreak_proto_rawDescGZIP() []byte {
	file_plugin_proto_tfbreak_proto_rawDescOnce.Do(func() {
		file_plugin_proto_tfbreak_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_tfbreak_proto_rawDesc), len(file_plugin_proto_tfbreak_proto_rawDesc)))
	})
	return file_plugin_proto_tfbreak_proto_rawDescData
}

var file_plugin_proto_tfbreak_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_plugin_proto_tfbreak_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_plugin_proto_tfbreak_proto_goTypes = []any{
	(Severity)(0),                         // 0: tfbreak.Severity
	(SchemaMode)(0),                       // 1: tfbreak.SchemaMode
	(ModuleCtxType)(0),                    // 2: tfbreak.ModuleCtxType
	(ExpandMode)(0),                       // 3: tfbreak.ExpandMode
	(*GetRuleSetName)(nil),                // 4: tfbreak.GetRuleSetName
	(*GetRuleSetVersion)(nil),             // 5: tfbreak.GetRuleSetVersion
	(*GetRuleNames)(nil),                  // 6: tfbreak.GetRuleNames
	(*GetVersionConstraint)(nil),          // 7: tfbreak.GetVersionConstraint
	(*GetConfigSchema)(nil),               // 8: tfbreak.GetConfigSchema
	(*ApplyGlobalConfig)(nil),             // 9: tfbreak.ApplyGlobalConfig
	(*ApplyConfig)(nil),                   // 10: tfbreak.ApplyConfig
	(*Check)(nil),                         // 11: tfbreak.Check
	(*GetModuleContent)(nil),              // 12: tfbreak.GetModuleContent
	(*GetResourceContent)(nil),            // 13: tfbreak.GetResourceContent
	(*EmitIssue)(nil),                     // 14: tfbreak.EmitIssue
	(*DecodeRuleConfig)(nil),              // 15: tfbreak.DecodeRuleConfig
	(*Config)(nil),                        // 16: tfbreak.Config
	(*RuleConfig)(nil),                    // 17: tfbreak.RuleConfig
	(*Rule)(nil),                          // 18: tfbreak.Rule
	(*BodySchema)(nil),                    // 19: tfbreak.BodySchema
	(*AttributeSchema)(nil),               // 20: tfbreak.AttributeSchema
	(*BlockSchema)(nil),                   // 21: tfbreak.BlockSchema
	(*BodyContent)(nil),                   // 22: tfbreak.BodyContent
	(*Attribute)(nil),                     // 23: tfbreak.Attribute
	(*Block)(nil),                         // 24: tfbreak.Block
	(*Range)(nil),                         // 25: tfbreak.Range
	(*Position)(nil),                      // 26: tfbreak.Position
	(*GetModuleContentOption)(nil),        // 27: tfbreak.GetModuleContentOption
	(*GetRuleSetName_Request)(nil),        // 28: tfbreak.GetRuleSetName.Request
	(*GetRuleSetName_Response)(nil),       // 29: tfbreak.GetRuleSetName.Response
	(*GetRuleSetVersion_Request)(nil),     // 30: tfbreak.GetRuleSetVersion.Request
	(*GetRuleSetVersion_Response)(nil),    // 31: tfbreak.GetRuleSetVersion.Response
	(*GetRuleNames_Request)(nil),          // 32: tfbreak.GetRuleNames.Request
	(*GetRuleNames_Response)(nil),         // 33: tfbreak.GetRuleNames.Response
	(*GetVersionConstraint_Request)(nil),  // 34: tfbreak.GetVersionConstraint.Request
	(*GetVersionConstraint_Response)(nil), // 35: tfbreak.GetVersionConstraint.Response
	(*GetConfigSchema_Request)(nil),       // 36: tfbreak.GetConfigSchema.Request
	(*GetConfigSchema_Response)(nil),      // 37: tfbreak.GetConfigSchema.Response
	(*ApplyGlobalConfig_Request)(nil),     // 38: tfbreak.ApplyGlobalConfig.Request
	(*ApplyGlobalConfig_Response)(nil),    // 39: tfbreak.ApplyGlobalConfig.Response
	(*ApplyConfig_Request)(nil),           // 40: tfbreak.ApplyConfig.Request
	(*ApplyConfig_Response)(nil),          // 41: tfbreak.ApplyConfig.Response
	(*Check_Request)(nil),                 // 42: tfbreak.Check.Request
	(*Check_Response)(nil),                // 43: tfbreak.Check.Response
	(*GetModuleContent_Request)(nil),      // 44: tfbreak.GetModuleContent.Request
	(*GetModuleContent_Response)(nil),     // 45: tfbreak.GetModuleContent.Response
	(*GetResourceContent_Request)(nil),    // 46: tfbreak.GetResourceContent.Request
	(*GetResourceContent_Response)(nil),   // 47: tfbreak.GetResourceContent.Response
	(*EmitIssue_Request)(nil),             // 48: tfbreak.EmitIssue.Request
	(*EmitIssue_Response)(nil),            // 49: tfbreak.EmitIssue.Response
	(*DecodeRuleConfig_Request)(nil),      // 50: tfbreak.DecodeRuleConfig.Request
	(*DecodeRuleConfig_Response)(nil),     // 51: tfbreak.DecodeRuleConfig.Response
	nil,                                   // 52: tfbreak.Config.RulesEntry
	nil,                                   // 53: tfbreak.BodyContent.AttributesEntry
}
var file_plugin_proto_tfbreak_proto_depIdxs = []int32{
	52, // 0: tfbreak.Config.rules:type_name -> tfbreak.Config.RulesEntry
	0,  // 1: tfbreak.Rule.severity:type_name -> tfbreak.Severity
	20, // 2: tfbreak.BodySchema.attributes:type_name -> tfbreak.AttributeSchema
	21, // 3: tfbreak.BodySchema.blocks:type_name -> tfbreak.BlockSchema
	1,  // 4: tfbreak.BodySchema.mode:type_name -> tfbreak.SchemaMode
	19, // 5: tfbreak.BlockSchema.body:type_name -> tfbreak.BodySchema
	53, // 6: tfbreak.BodyContent.attributes:type_name -> tfbreak.BodyContent.AttributesEntry
	24, // 7: tfbreak.BodyContent.blocks:type_name -> tfbreak.Block
	25, // 8: tfbreak.Attribute.range:type_name -> tfbreak.Range
	25, // 9: tfbreak.Attribute.name_range:type_name -> tfbreak.Range
	22, // 10: tfbreak.Block.body:type_name -> tfbreak.BodyContent
	25, // 11: tfbreak.Block.def_range:type_name -> tfbreak.Range
	25, // 12: tfbreak.Block.type_range:type_name -> tfbreak.Range
	25, // 13: tfbreak.Block.label_ranges:type_name -> tfbreak.Range
	26, // 14: tfbreak.Range.start:type_name -> tfbreak.Position
	26, // 15: tfbreak.Range.end:type_name -> tfbreak.Position
	2,  // 16: tfbreak.GetModuleContentOption.module_ctx:type_name -> tfbreak.ModuleCtxType
	3,  // 17: tfbreak.GetModuleContentOption.expand_mode:type_name -> tfbreak.ExpandMode
	19, // 18: tfbreak.GetConfigSchema.Response.schema:type_name -> tfbreak.BodySchema
	16, // 19: tfbreak.ApplyGlobalConfig.Request.config:type_name -> tfbreak.Config
	22, // 20: tfbreak.ApplyConfig.Request.content:type_name -> tfbreak.BodyContent
	19, // 21: tfbreak.GetModuleContent.Request.schema:type_name -> tfbreak.BodySchema
	27, // 22: tfbreak.GetModuleContent.Request.option:type_name -> tfbreak.GetModuleContentOption
	22, // 23: tfbreak.GetModuleContent.Response.content:type_name -> tfbreak.BodyContent
	19, // 24: tfbreak.GetResourceContent.Request.schema:type_name -> tfbreak.BodySchema
	27, // 25: tfbreak.GetResourceContent.Request.option:type_name -> tfbreak.GetModuleContentOption
	22, // 26: tfbreak.GetResourceContent.Response.content:type_name -> tfbreak.BodyContent
	18, // 27: tfbreak.EmitIssue.Request.rule:type_name -> tfbreak.Rule
	25, // 28: tfbreak.EmitIssue.Request.range:type_name -> tfbreak.Range
	17, // 29: tfbreak.Config.RulesEntry.value:type_name -> tfbreak.RuleConfig
	23, // 30: tfbreak.BodyContent.AttributesEntry.value:type_name -> tfbreak.Attribute
	28, // 31: tfbreak.RuleSet.GetRuleSetName:input_type -> tfbreak.GetRuleSetName.Request
	30, // 32: tfbreak.RuleSet.GetRuleSetVersion:input_type -> tfbreak.GetRuleSetVersion.Request
	32, // 33: tfbreak.RuleSet.GetRuleNames:input_type -> tfbreak.GetRuleNames.Request
	34, // 34: tfbreak.RuleSet.GetVersionConstraint:input_type -> tfbreak.GetVersionConstraint.Request
	36, // 35: tfbreak.RuleSet.GetConfigSchema:input_type -> tfbreak.GetConfigSchema.Request
	38, // 36: tfbreak.RuleSet.ApplyGlobalConfig:input_type -> tfbreak.ApplyGlobalConfig.Request
	40, // 37: tfbreak.RuleSet.ApplyConfig:input_type -> tfbreak.ApplyConfig.Request
	42, // 38: tfbreak.RuleSet.Check:input_type -> tfbreak.Check.Request
	44, // 39: tfbreak.Runner.GetOldModuleContent:input_type -> tfbreak.GetModuleContent.Request
	44, // 40: tfbreak.Runner.GetNewModuleContent:input_type -> tfbreak.GetModuleContent.Request
	46, // 41: tfbreak.Runner.GetOldResourceContent:input_type -> tfbreak.GetResourceContent.Request
	46, // 42: tfbreak.Runner.GetNewResourceContent:input_type -> tfbreak.GetResourceContent.Request
	48, // 43: tfbreak.Runner.EmitIssue:input_type -> tfbreak.EmitIssue.Request
	50, // 44: tfbreak.Runner.DecodeRuleConfig:input_type -> tfbreak.DecodeRuleConfig.Request
	29, // 45: tfbreak.RuleSet.GetRuleSetName:output_type -> tfbreak.GetRuleSetName.Response
	31, // 46: tfbreak.RuleSet.GetRuleSetVersion:output_type -> tfbreak.GetRuleSetVersion.Response
	33, // 47: tfbreak.RuleSet.GetRuleNames:output_type -> tfbreak.GetRuleNames.Response
	35, // 48: tfbreak.RuleSet.GetVersionConstraint:output_type -> tfbreak.GetVersionConstraint.Response
	37, // 49: tfbreak.RuleSet.GetConfigSchema:output_type -> tfbreak.GetConfigSchema.Response
	39, // 50: tfbreak.RuleSet.ApplyGlobalConfig:output_type -> tfbreak.ApplyGlobalConfig.Response
	41, // 51: tfbreak.RuleSet.ApplyConfig:output_type -> tfbreak.ApplyConfig.Response
	43, // 52: tfbreak.RuleSet.Check:output_type -> tfbreak.Check.Response
	45, // 53: tfbreak.Runner.GetOldModuleContent:output_type -> tfbreak.GetModuleContent.Response
	45, // 54: tfbreak.Runner.GetNewModuleContent:output_type -> tfbreak.GetModuleContent.Response
	47, // 55: tfbreak.Runner.GetOldResourceContent:output_type -> tfbreak.GetResourceContent.Response
	47, // 56: tfbreak.Runner.GetNewResourceContent:output_type -> tfbreak.GetResourceContent.Response
	49, // 57: tfbreak.Runner.EmitIssue:output_type -> tfbreak.EmitIssue.Response
	51, // 58: tfbreak.Runner.DecodeRuleConfig:output_type -> tfbreak.DecodeRuleConfig.Response
	45, // [45:59] is the sub-list for method output_type
	31, // [31:45] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_plugin_proto_tfbreak_proto_init() }
func file_plugin_proto_tfbreak_proto_init() {
	if File_plugin_proto_tfbreak_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_tfbreak_proto_rawDesc), len(file_plugin_proto_tfbreak_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_tfbreak_proto_goTypes,
		DependencyIndexes: file_plugin_proto_tfbreak_proto_depIdxs,
		EnumInfos:         file_plugin_proto_tfbreak_proto_enumTypes,
		MessageInfos:      file_plugin_proto_tfbreak_proto_msgTypes,
	}.Build()
	File_plugin_proto_tfbreak_proto = out.File
	file_plugin_proto_tfbreak_proto_goTypes = nil
	file_plugin_proto_tfbreak_proto_depIdxs = nil
}
